namespace: datastore
appname: jupyter-hub
image: cloudcheflabs/spring-simple-jupyter-hub:latest
imagePullPolicy: Always
replicas: 3
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 5Gi
priorityClassName: ""
annotations: {}
affinity: {}
tolerations: {}
nodeSelector: {}
hostNetwork: false

# hpa.
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

# spring boot server port.
server:
  port : 8080

# node port.
nodePort: 32080

# spring profile.
spring:
  profiles:
    active: dev


# spring boot management server.
management:
  server:
    port: 18081

# readiness probe.
readiness:
  initialDelaySeconds: 15
  periodSeconds: 10

# liveness probe.
liveness:
  initialDelaySeconds: 3
  periodSeconds: 10

# java opts.
javaOpts: "-Xmx4G"

# cert-manager.
certManager:
  clusterIssue: letsencrypt-prod

# ingress.
ingress:
  enabled: false
  ingressClassName: nginx
  hostName: dev-spring-simple.cloudchef-labs.com
  path: /

# image pull secret.
imagePullSecret: simple-reg-cred
