apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.namespace }}
    component: simple-spring-boot
data:
  application.yml: |
    ---
    #####################
    # profile: common
    #####################
    
    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
        db:
          enabled: false
      server:
        port: {{ .Values.management.server.port }}
    
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: /
      shutdown: graceful
      error:
        include-message: always
    
    ---
    #####################
    # profile: dev
    #####################
    spring:
      config:
        activate:
          on-profile: dev
    
    ---
    #####################
    # profile: stg
    #####################
    spring:
      config:
        activate:
          on-profile: stg
    
    
    ---
    #####################
    # profile: prod
    #####################
    spring:
      config:
        activate:
          on-profile: prod
    
    

        