apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    component: simple-spring-boot
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      component: simple-spring-boot
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: simple-spring-boot
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ .Values.appname }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Values.appname }}
          image: {{ .Values.image }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profiles.active }}"
            - name: JAVA_OPTS
              value: "{{ .Values.javaOpts }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            privileged: true
            runAsUser: 0
          resources: 
          {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: simple-spring-boot-conf-volume
              mountPath: /opt/simple-spring-boot/conf/application.yml
              subPath: application.yml
          ports:
            - name: rest
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.management.server.port }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.management.server.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "15" ]
      volumes:
        - name: simple-spring-boot-conf-volume
          configMap:
            name: {{ .Values.appname }}