{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.namespace }}-ingress"
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssue }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: "Prefix"
            backend:
              serviceName: "{{ .Values.namespace }}-service"
              servicePort: {{ .Values.server.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
      secretName: {{ .Values.ingress.hostName }}-tls
{{- end }}