---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appname }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
    component: simple-spring-boot
spec:
  type: NodePort
  ports:
    - port: {{ .Values.server.port }}
      nodePort: {{ .Values.nodePort }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    app: {{ .Values.appname }}
